<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>witch-hat-white.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="witch-hat-white.ico" />
    <None Remove="witch-hat-white.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FontAwesome5" Version="2.1.4" />
    <PackageReference Include="MahApps.Metro" Version="2.4.9" />
    <PackageReference Include="SharpClipboard" Version="3.5.2" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="witch-hat-white.ico" />
    <Resource Include="witch-hat-white.png" />
  </ItemGroup>
</Project>